# Generated by Django 3.2.5 on 2021-07-20 06:11

import cafe.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter your menu', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter your menu', max_length=30)),
                ('price', models.IntegerField(help_text='enetr the price(cant)', validators=[cafe.models.menu_Item_price_validator], verbose_name='price(toman)')),
                ('Discount', models.IntegerField(default=0, help_text='enter the Discount', verbose_name='Discount')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_f', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('date_t', models.DateTimeField(auto_now=True, verbose_name='date_time')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('menu_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='enter your Table')),
                ('cafe_space_position', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('time_stamp', models.TimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.user')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.table'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.table'),
        ),
    ]
